name: cloudrun-deploy
on:
  push:
    branches:
      - master
jobs:
  setup-build-deploy: 
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - uses: google-github-actions/auth@v1
      with:
        service_account: ${{ secrets.GCP_EMAIL }}
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker
    
    - name: Build
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.DOCKER_IMAGE }}:latest .

    - name: Push
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.DOCKER_IMAGE }}:latest

    - name: Deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ secrets.GCP_SERVICE_NAME }}
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.DOCKER_IMAGE }}:latest

    - name: 'Use output'
      run: echo ${{ steps.deploy.outputs.url }}